### ISSUE TITLE
createrelayhere generates an error

### ISSUE THREAD

**Issue by wingzero54** [CivClassic/Kira#12]
![image](https://user-images.githubusercontent.com/7980903/101400191-2a3fb480-3896-11eb-95c5-fd01e3e12342.png)

**Comment by KaloHG** [comment]
The related line (Line 51, CreateRelayChannelHereCommand.java) fetches the permissions of a user and puts it into an EnumSet. The only way this could be a nullpointer, is if someone attempted to set up a relay in Private Messages (I think?), or if somehow the person is requesting a relay for a channel they are not in. 

i.e. gonna need more info on this one wing, it makes literally no sense why this is returning null.

**Comment by wingzero54** [comment]
Brit was attempting to create a relay for a citadel group he was in and had the kira permission for, and it was not working and threw this error

**Comment by KaloHG** [comment]
could you get more information about the channel, as well as the group?

Does this only occur with that specific citadel group? Or only that specific channel.

**Comment by wingzero54** [comment]
> could you get more information about the channel, as well as the group?
> 
> Does this only occur with that specific citadel group? Or only that specific channel.

It appears that any attempt to use "createrelayhere" in any channel or with any group throws this error, the command is totally broken right now.

**Comment by KaloHG** [comment]
Discord must've changed something related to the API.

**Comment by wingzero54** [comment]
This was fixed, I believe by this commit but maybe another one around the same time https://github.com/CivClassic/Kira/commit/cf7cbd47fa7fe766c8bb7607bc455cfeff15b962
