### ISSUE TITLE
escape formatting characters

### ISSUE THREAD

**Issue by Gjum** [CivClassic/Kira#13]
underscores in player names, mentions in chat messages, etc

**Comment by Protonull** [comment]
Must've missed the conversation about this. What do you mean and could you give an example, like a before and after?

**Comment by wingzero54** [comment]
![Here's an example](https://user-images.githubusercontent.com/7980903/117673084-12839980-b170-11eb-9adb-edf3d3f6e39a.png). Any names with underscores, when Kira prints them into discord they take on discord formatting. Looks like the relay already has some kind of escape characters (as snitches or chat do not trigger discord formatting). But anything you do with Kira directly in discord will take on formatting.
