### ISSUE TITLE
2fa error

### ISSUE THREAD

**Issue by wingzero54** [CivClassic/Kira#15]
ERROR Main Exception in rabbit listener
net.dv8tion.jda.api.exceptions.ErrorResponseException: 60003: Two Factor is required for this operation

Getting the above error when trying to create relays in the official discord, and sometimes when relaying various messages too.

**Comment by KaloHG** [comment]
this can only be fixed if the creator of the bot (Maxopoly) enables 2FA on their account. this is likely due to server settings on the discord where the relay is being created. tell the owner to disable the 2FA requirement for the moderation in the server

edit: this means that this is not an issue with the code/bot, it's an issue with the developer/server owner.

**Comment by KaloHG** [comment]
please close this issue as it is not a bug, I iterated how to fix the error message above.

in this instance contact Maxopoly and ask him to enable 2FA on his account, **or** have the bot be verified via the Discord Application page, follow the instructions here: https://support.discord.com/hc/en-us/articles/360040720412-Bot-Verification-and-Data-Whitelisting#how-do-i-start-the-process

thank you.

**Comment by wingzero54** [comment]
The issue is here for documentation, this is where we track issues. I do not own the kira bot so I cannot resolve this issue, and I don't want it to get forgotten like all the other issues that pile up and in 12 months people are like "oh yeah, I think that might have been an issue did we ever fix it?"

**Comment by TheRealArchie** [comment]
hurrdurr just remember all the issues you cant fix ezpz

**Comment by wingzero54** [comment]
OK so we figured out what causes this - the 2fa error is coming from Kira trying to delete the duplicate messages in relay channels. It's why Kira can't delete the duplicate messages anymore (or sometimes can't?)

**Comment by wingzero54** [comment]
Max did not have 2fa turned on. He turned on 2fa and this is resolved.
